### ISSUE TITLE
Issues with IO::Handle and perl 5.10

### ISSUE THREAD

**Issue by cjfields** [rvosa/bio-phylo#19]
In BioPerl we're seeing some issues with Bio::Phylo using perl v 5.10:

https://travis-ci.org/bioperl/bioperl-live/jobs/47662896

Same in CPAN Testers for Bio::Phylo:

http://www.cpantesters.org/cpan/report/87d57d52-6bf9-1014-99a2-46f257c061e0

Seems very specific to the IO::Handle version, so maybe the fix is to require at least IO::Handle 1.28 (the one released w/ perl 5.12, which passes.  May test this in BioPerl via Travis-CI

**Comment by cjfields** [comment]
May be more complicated than that; seems to pop up only under certain circumstances.  Only one BioPerl test appears to be failing at the moment, so I can focus on that.

**Comment by rvosa** [comment]
Thanks! If you figure out what is happening let me know and I'll push out a
fix.

**Comment by rvosa** [comment]
Hi @cjfields - did you ever manage to figure this out?

**Comment by rvosa** [comment]
I looked at the failing logs and for some reason it is unhappy about me doing `$handle->eof()` because I am getting `Can't find object method...` errors. However, I should equally be able to use the built in function, i.e. change the idiom to `eof $handle`. This appears to pass the tests on my end on travis (including 5.10) so I wonder if this is any help on your end?

**Comment by cjfields** [comment]
May need to check but I would assume this should fix it.  Let me add a pointer to this in the bioperl issues queue.

**Comment by cjfields** [comment]
@rvosa I think this is a non-issue, apparently the travis test was rerun and doesn't show the same problem, I would ignore it.  Closing this ticket.
